### ISSUE TITLE
Undefined Namespace Prefix for DOMXPath::query()

### ISSUE THREAD

**Issue by robxu9** [bramley/phplist-plugin-contentareas#1]
Hey there, this is a really great plugin! It's honestly just what we needed for our newsletters.

We're having a small problem - when we try to view bounces, and the message sent, this shows up:

```
DOMXPath::query(): Undefined namespace prefix

#0 [internal function]: phpList\plugin\Common\Exception::errorHandler(2, 'DOMXPath::query...', '/home/user-data...', 318, Array)
#1 /home/user-data/www/chinablue.rxu.io/admin/plugins/CommonPlugin/vendor/pelago/emogrifier/Classes/Emogrifier.php(318): DOMXPath->query('//*[contains(co...')
#2 /home/user-data/www/chinablue.rxu.io/admin/plugins/ContentAreas/TemplateModel.php(152): Pelago\Emogrifier->emogrify()
#3 /home/user-data/www/chinablue.rxu.io/admin/plugins/ContentAreas/TemplateModel.php(181): phpList\plugin\ContentAreas\TemplateModel->merge(Array, false)
#4 /home/user-data/www/chinablue.rxu.io/admin/plugins/ContentAreas/MessageController.php(31): phpList\plugin\ContentAreas\TemplateModel::mergeTemplate('<!DOCTYPE html ...', '7')
#5 /home/user-data/www/chinablue.rxu.io/admin/plugins/Common/Controller.php(90): phpList\plugin\ContentAreas\MessageController->actionPreview()
#6 /home/user-data/www/chinablue.rxu.io/admin/plugins/Common/Main.php(44): phpList\plugin\Common\Controller->run('preview')
#7 /home/user-data/www/chinablue.rxu.io/admin/plugins/ContentAreas/message_page.php(18): phpList\plugin\Common\Main::run(Object(phpList\plugin\ContentAreas\ControllerFactory))
#8 /home/user-data/www/chinablue.rxu.io/admin/index.php(525): include('/home/user-data...')
#9 {main}

Navigation

Recently Visited

View bounces
Manage bounces
Send the queue
View opens
Statistics overview
Statistics overview

© phpList ltd. - v3.0.12
Resources  |  
```

I believe it's because DOMXPath isn't declared early enough, but I didn't look closely enough.

**Comment by bramley** [comment]
Do you get the same problem when composing a new message using the same template, and then click the Preview button? 

I guess that there is something in the css within your template that causes the problem. You can disable this processing through the Settings page. Change "Automatically inline css" from Yes to No.

Can you copy your template here or maybe into a Gist https://gist.github.com/ , if it is not private, so that I can try to reproduce the problem?

**Comment by robxu9** [comment]
Yeah, sure! I can copy the template, no problem. It's not exactly private if we send it out.
https://gist.github.com/robxu9/b73839710461ff597aff

**Comment by bramley** [comment]
The CSS in the template uses quite a few selectors that are not supported, such as nth-last-child. See https://github.com/jjriv/emogrifier#supported-css-selectors for those that are supported.

But your html already has styles applied so this feature of the plugin isn't going to be that useful anyway. You should disable inline css on the Settings page.

**Comment by robxu9** [comment]
Okay, thanks for your help!

**Comment by robxu9** [comment]
Just wanted to follow up on this - if I disable inline CSS, then we lose all the styles on the markup that we put in the content areas. So we've decided to just deal with it and keep inline CSS enabled.

Unfortunately, we lose all the markup regardless with `[CONTENT]`, but that's unfortunate.

**Comment by bramley** [comment]
The original problem seems to be caused by the pseudo classes such as nth-last-child due to the ':' between that and the preceding element. If you remove all of the rules that include those, such as this one then the error doesn't happen.

```
.one-col .column table:nth-last-child(2) td h1:last-child,
.one-col .column table:nth-last-child(2) td h2:last-child,
.one-col .column table:nth-last-child(2) td h3:last-child,
.one-col .column table:nth-last-child(2) td p:last-child,
.one-col .column table:nth-last-child(2) td ol:last-child,
.one-col .column table:nth-last-child(2) td ul:last-child {
  Margin-bottom: 24px;
}
```

But I cannot tell whether the layout has now changed substantially.
