### ISSUE TITLE
Edit Areas tab missing

### ISSUE THREAD

**Issue by magdacorreia** [bramley/phplist-plugin-contentareas#10]
I've started using phplist a few months ago. I have a ubuntu server with php 7.0 with DOM and XSL enabled.
My phplist server has 3.4.1 version with CKEditorPlugin enabled and i've also installed CommonPlugin and ViewBrowserPlugin both at 2.10 version.

Despite all that the "Edit Areas" tab don't appear when i edit a Campaign.
I don't have any related log on phplist log system.

Can you help me please.

**Comment by bramley** [comment]
The additional tab will appear only when the template contains some content areas, https://resources.phplist.com/plugin/contentareas#identifying_content_areas
If the plugin does not find any content areas then the additional tab is not displayed.
