### ISSUE TITLE
Can't locate PreMailerAbstract.php in ContentAreas

### ISSUE THREAD

**Issue by rayvolvez** [bramley/phplist-plugin-contentareas#4]
Dear Duncan,

Sorry it's me again.

I'm having issues getting the emails to show up appropriately in outlook. The table tags all appeared with < td and there are alot of gibberish.

This is the error I get from server logs, couldn't locate the said php file in Content Areas plugin, able to advise?

[Mon Jan 25 23:11:59 2016] [error] [client 113.29.225.10] PHP Warning: DOMDocument::loadHTML(): Unexpected end tag : p in Entity, line: 402 in /var/www/vhosts/(domain)/httpdocs/mail/admin/plugins/ContentAreas/vendor/crossjoin/pre-mailer/src/Crossjoin/PreMailer/PreMailerAbstract.php on line 237 

Thank you!

**Comment by bramley** [comment]
There looks to be an erroneous end p tag in the template. I don't think it is mentioned but the template must be correct HTML.

Getting emails to display sensibly in Outlook can be difficult. You might have to change the encoding from quoted-printable to 8-bit (see https://resources.phplist.com/system/config/htmlemail_encoding), and ensure that there are not any long lines (probably < 1000 characters). The package phpmailer, which is used by phplist, will now use quoted-printable when lines are longer than the maximum specified by SMTP, but I don't remember the exact limit.

**Comment by rayvolvez** [comment]
Dear Duncan,
Have actually duplicated the most basic system template, just added in the data-edit tag for one of the element. Checked that there is no p issue.

The funny thing is, I had the exact same php installation across two servers, using the exact same plugins and templates, emails from one of the server just refused to display properly in outlook. One is actually fine.

By any chance, would you be able to advise on this error, sorry if this is off-thread:
PHP Fatal error: Uncaught exception 'ErrorException' with message 'curl_setopt(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set' in /var/www/vhosts/(domain)/httpdocs/mail/admin/lib.php:1050\nStack trace:\n#0 [internal function]: phpList\\plugin\\Common\\Exception::errorHandler(2, 'curl_setopt(): ...', '/var/www/vhosts...', 1050, Array)\n#1 /var/www/vhosts/(domain)/httpdocs/mail/admin/lib.php(1050): curl_setopt(Resource id #162, 52, 1)\n#2 /var/www/vhosts/(domain)/httpdocs/mail/admin/send_core.php(1165): testUrl('http://(domain)...')\n#3 /var/www/vhosts/(domain)/httpdocs/mail/admin/send.php(117): include('/var/www/vhosts...')\n#4 /var/www/vhosts/(domain)/httpdocs/mail/admin/index.php(631): include('/var/www/vhosts...')\n#5 {main}\n thrown in /var/www/vhosts/(domain)/httpdocs/mail/admin/lib.php on line 1050, referer: http://(domain)/mail/admin/?page=send&id=33&tk=7b538&tab=Content

Thanks!

**Comment by rayvolvez** [comment]
Dear Duncan,

I think it is worth mentioning that preview does render everything correctly. Hmmmm :(
Somehow I fear that this is more server related than phplist.

**Comment by bramley** [comment]
Is there an issue with the plugin? This isn't the place ask for support (the forum is a better place for that).
