### ISSUE TITLE
Fatal error: Call to a member function appendChild() when switching to Edit Areas Tab

### ISSUE THREAD

**Issue by fwolfst** [bramley/phplist-plugin-contentareas#6]
Using phpList 3.3.1 with plugin from master.zip today . At first everything looks as if it works, but as soon as I change the template (with the built-in editor), following error message is displayed instead of the template when I want to "Edit Areas" in a campaign:

Fatal error: Call to a member function appendChild() on null in /path/to/public_html/lists/admin/plugins/ContentAreas/TemplateModel.php on line 176
phpList version 3.3.1

**Comment by bramley** [comment]
Most likely editing the template using the phplist editor has altered the structure in some way. If you view the template in a text editor then you might be able to see what is wrong. I recommend editing these templates only in a text editor not within phplist.

If the template is not private can you attach it here?

**Comment by bramley** [comment]
The problem seems to be that your template doesn't have a head element. Is that the case?

**Comment by fwolfst** [comment]
I used the sample template and just inserted a

`<img data-edit="image_1" style="width: 150px; height: 150px;"  />`

below the main heading (but where and which change is irrelevant actually)


However, you were right with your observations, if uploaded (in contrast to
inline-edited) it works. Btw I was always using the "source" view of the
editor when editing the template.


On Fri, Mar 17, 2017 at 10:46 AM, Duncan Cameron <notifications@github.com>
wrote:
>
> Most likely editing the template using the phplist editor has altered the
structure in some way. If you view the template in a text editor then you
might be able to see what is wrong. I recommend editing these templates
only in a text editor not within phplist.

**Comment by fwolfst** [comment]
Also right, when editing the template via the built-in editor and changing to source view, the html boilerplate is gone (I guess that is intentional) - probably something to be fixed in phplist itself - however I can imagine that there are valid reasons to do it this way; the header is most likely generated outside the template.

**Comment by bramley** [comment]
Which editor are you using? I suspect fckeditor which does remove some of the html structure. If you switch to using the CKEditor plugin then you should be able to edit the template within phplist, but I still recommend editing using a text editor.

**Comment by fwolfst** [comment]
The installation is very vanilla - so I guess thats fckeditor. Thank you
for your support. I suggest to put a warning in the "manage-template"
section and in the readme.

**Comment by bramley** [comment]
Yes, I will revise the documentation to recommend not using fckeditor. 

Also the code might be able to be more robust, I will look at that. But if the error had not been reported then you would have been using a template with parts of it removed, possibly making it more difficult to identify the underlying problem.
