### ISSUE TITLE
Editor does not always load

### ISSUE THREAD

**Issue by bartkummel** [bramley/phplist-plugin-contentareas#7]
Hi,

I have a problem with this plugin: the first time I click on a pencil icon, instead of the WYSIWYG editor, a tiny text field is shown. Only after closing the popup by clicking the "x" in the upper right corner and clicking the pencil icon again, the editor will show. This repeats for every content area. I am using TinyMCE as editor. I hope this can be fixed, as I will have a hard time explaining this behaviour to my users... ;-)

Best regards,
Bart

**Comment by bramley** [comment]
I don't actively use TinyMCE so don't know when this stopped working properly.

You can try installing a local copy of TinyMCE by downloading the TinyMCE Community version from https://www.tinymce.com/download/
Then on the Settings page enter the URL to tinymce.min.js

**Comment by bramley** [comment]
The probable cause of the problem is loading TinyMCE remotely from a different host to where your phplist is installed. Using a local copy of TinyMCE as I suggested should avoid that.

**Comment by bramley** [comment]
@bartkummel Did you try using a local copy of TinyMCE? If so, did that resolve the problem?

**Comment by bartkummel** [comment]
Hi @bramley , unfortunately, I did not have the time to try that. I'll update this issue as soon as I've tried it.

**Comment by bartkummel** [comment]
Hi @bramley, I finally found some time to test the issue with a locally installed TinyMCE. And you were right: no loading problems with the locally installed TinyMCE. As for me, I can live with this work around. Perhaps you should add to the documentation that a TinyMCE from the CDN might cause trouble in combination with content areas. Sorry for the delay, thanks for the patience!
